/*
 * Command Center Design: Configure Page
 * - Left panel: scenario parameters (role, difficulty, mode)
 * - Right panel: live preview of generated scenario card
 * - Now uses real AI-powered scenario generation via tRPC
 */

import NavHeader from "@/components/NavHeader";
import { Button } from "@/components/ui/button";
import { useSimulator, type ScenarioCard } from "@/contexts/SimulatorContext";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { allScenarioFamilies, familyLabels } from "@shared/wsc-content";
import { departmentRoles } from "@/features/simulator/config";
import { motion } from "framer-motion";
import { useState } from "react";
import { toast } from "sonner";
import {
  Settings,
  Zap,
  ArrowRight,
  Phone,
  Users,
  AlertTriangle,
  Loader2,
} from "lucide-react";

const SCENARIO_BG = "https://d2xsxph8kpxj0f.cloudfront.net/310519663357120672/T7ShWeUdbGNTJEK77SyZhN/scenario-card-bg-csGegWfyTSzQxrEJPXuyjY.webp";

const difficultyLabels: Record<number, { label: string; color: string; desc: string }> = {
  1: { label: "BASIC", color: "text-success", desc: "Friendly customer, simple question" },
  2: { label: "MODERATE", color: "text-teal", desc: "Mildly confused, needs explanation" },
  3: { label: "CHALLENGING", color: "text-amber", desc: "Frustrated, needs empathy + policy" },
  4: { label: "ADVANCED", color: "text-amber", desc: "Angry, hidden facts, escalation likely" },
  5: { label: "CRITICAL", color: "text-danger", desc: "Multi-layered crisis, demands manager" },
};

const scenarioFamilies = allScenarioFamilies;

export default function Configure() {
  const { config, setConfig, setScenario, setEvaluation, setCoaching, clearConversation } = useSimulator();
  const [, navigate] = useLocation();
  const [generatedScenario, setGeneratedScenario] = useState<ScenarioCard | null>(null);

  const generateMutation = trpc.simulator.generateScenario.useMutation({
    onSuccess: (data) => {
      const scenario = data.scenario as ScenarioCard;
      setGeneratedScenario(scenario);
      toast.success("Scenario generated by AI");
    },
    onError: (err) => {
      toast.error(`Generation failed: ${err.message}`);
    },
  });

  const handleGenerate = () => {
    generateMutation.mutate({
      department: (config.department as "customer_service" | "golf" | "mod_emergency" | undefined) ?? "customer_service",
      employeeRole: config.employeeRole,
      difficulty: config.difficulty,
      mode: config.mode === "phone" ? "phone" : config.mode === "live-voice" ? "live_voice" : "in_person",
    });
  };

  const handleLaunch = () => {
    if (!generatedScenario) return;
    setScenario(generatedScenario);
    setEvaluation(null);
    setCoaching(null);
    clearConversation();
    navigate("/practice/session");
  };

  const diff = difficultyLabels[config.difficulty];
  const isGenerating = generateMutation.isPending;

  return (
    <div className="min-h-screen bg-background">
      <NavHeader />

      <div className="pt-14">
        <div className="container py-8">
          {/* Page Header */}
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
            className="flex items-center gap-3 mb-8"
          >
            <div className="w-10 h-10 rounded-md bg-teal/10 border border-teal/30 flex items-center justify-center">
              <Settings className="w-5 h-5 text-teal" />
            </div>
            <div>
              <h1 className="text-2xl font-bold">Configure Scenario</h1>
              <p className="text-sm text-muted-foreground">Set parameters and generate a training scenario</p>
            </div>
          </motion.div>

          <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
            {/* Left: Configuration Panel */}
            <motion.div
              className="lg:col-span-2"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.3, delay: 0.1 }}
            >
              <div className="panel p-6 space-y-6">
                <div className="flex items-center gap-2 mb-2">
                  <span className="status-dot bg-teal" />
                  <span className="font-mono text-xs text-teal tracking-wider uppercase">
                    Parameters
                  </span>
                </div>

                {/* Employee Role */}
                <div>
                  <label className="font-mono text-xs text-muted-foreground tracking-wider uppercase block mb-2">
                    Employee Role
                  </label>
                  <div className="grid grid-cols-1 gap-2">
                    {Object.values(departmentRoles).map((role) => (
                      <button
                        key={role}
                        onClick={() => setConfig({ ...config, employeeRole: role })}
                        className={`p-3 rounded-md border text-sm text-left transition-all duration-150 ${
                          config.employeeRole === role
                            ? "border-teal/50 bg-teal/10 text-teal"
                            : "border-border bg-secondary/30 text-muted-foreground hover:bg-secondary/50"
                        }`}
                      >
                        <div className="flex items-center gap-2">
                          <Users className="w-4 h-4" />
                          {role}
                        </div>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Mode */}
                <div>
                  <label className="font-mono text-xs text-muted-foreground tracking-wider uppercase block mb-2">
                    Interaction Mode
                  </label>
                  <div className="grid grid-cols-2 gap-2">
                    {[
                      { value: "in-person" as const, label: "In-Person", icon: Users },
                      { value: "phone" as const, label: "Phone Call", icon: Phone },
                    ].map(({ value, label, icon: Icon }) => (
                      <button
                        key={value}
                        onClick={() => setConfig({ ...config, mode: value })}
                        className={`p-3 rounded-md border text-sm text-center transition-all duration-150 ${
                          config.mode === value
                            ? "border-teal/50 bg-teal/10 text-teal"
                            : "border-border bg-secondary/30 text-muted-foreground hover:bg-secondary/50"
                        }`}
                      >
                        <Icon className="w-4 h-4 mx-auto mb-1" />
                        {label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Difficulty */}
                <div>
                  <label className="font-mono text-xs text-muted-foreground tracking-wider uppercase block mb-2">
                    Difficulty Level
                  </label>
                  <div className="flex gap-2 mb-3">
                    {[1, 2, 3, 4, 5].map((level) => (
                      <button
                        key={level}
                        onClick={() => setConfig({ ...config, difficulty: level })}
                        className={`w-10 h-10 rounded-md border font-mono text-sm font-bold transition-all duration-150 ${
                          config.difficulty === level
                            ? "border-teal/50 bg-teal/10 text-teal"
                            : "border-border bg-secondary/30 text-muted-foreground hover:bg-secondary/50"
                        }`}
                      >
                        {level}
                      </button>
                    ))}
                  </div>
                  <div className={`flex items-center gap-2 text-sm ${diff.color}`}>
                    {config.difficulty >= 4 && <AlertTriangle className="w-3.5 h-3.5" />}
                    <span className="font-mono text-xs font-semibold tracking-wider">{diff.label}</span>
                    <span className="text-muted-foreground text-xs">— {diff.desc}</span>
                  </div>
                </div>

                {/* Scenario Families */}
                <div>
                  <label className="font-mono text-xs text-muted-foreground tracking-wider uppercase block mb-2">
                    Scenario Pool
                  </label>
                  <div className="flex flex-wrap gap-1.5">
                    {scenarioFamilies.map((f) => (
                      <span
                        key={f}
                        className="px-2 py-1 rounded text-[11px] bg-secondary/50 text-muted-foreground border border-border/50 font-mono"
                      >
                        {familyLabels[f] || f}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Generate Button */}
                <Button
                  onClick={handleGenerate}
                  disabled={isGenerating}
                  className="w-full bg-teal text-slate-deep hover:bg-teal/90 font-semibold gap-2"
                  size="lg"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      AI Generating...
                    </>
                  ) : (
                    <>
                      <Zap className="w-4 h-4" />
                      Generate Scenario
                    </>
                  )}
                </Button>
              </div>
            </motion.div>

            {/* Right: Scenario Preview */}
            <motion.div
              className="lg:col-span-3"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.3, delay: 0.2 }}
            >
              {!generatedScenario ? (
                <div
                  className="panel p-8 flex flex-col items-center justify-center min-h-[500px] relative overflow-hidden"
                >
                  <div
                    className="absolute inset-0 bg-cover bg-center opacity-20"
                    style={{ backgroundImage: `url(${SCENARIO_BG})` }}
                  />
                  <div className="relative text-center">
                    <Zap className="w-12 h-12 text-muted-foreground/30 mx-auto mb-4" />
                    <p className="text-muted-foreground text-sm">
                      Configure parameters and generate a scenario
                    </p>
                    <p className="text-muted-foreground/50 text-xs mt-2 font-mono">
                      AWAITING GENERATION
                    </p>
                  </div>
                </div>
              ) : (
                <div className="panel p-6 space-y-5">
                  {/* Scenario Header */}
                  <div className="flex items-start justify-between">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <span className="status-dot bg-success" />
                        <span className="font-mono text-xs text-success tracking-wider uppercase">
                          Scenario Ready
                        </span>
                      </div>
                      <h2 className="text-xl font-bold">{generatedScenario.customer_persona.name}</h2>
                      <p className="text-sm text-muted-foreground">{generatedScenario.customer_persona.membership_status}</p>
                    </div>
                    <div className="text-right">
                      <span className="font-mono text-xs text-muted-foreground">{generatedScenario.scenario_id}</span>
                      <div className={`font-mono text-xs font-bold mt-1 ${difficultyLabels[generatedScenario.difficulty]?.color || 'text-teal'}`}>
                        LVL {generatedScenario.difficulty}
                      </div>
                    </div>
                  </div>

                  {/* Issue Type */}
                  <div className="bg-secondary/30 rounded-md p-3 border border-border/50">
                    <span className="font-mono text-[10px] text-amber tracking-wider uppercase">Issue Type</span>
                    <p className="text-sm mt-1">{generatedScenario.issue_type}</p>
                  </div>

                  {/* Situation Summary */}
                  <div>
                    <span className="font-mono text-[10px] text-muted-foreground tracking-wider uppercase">Situation</span>
                    <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
                      {generatedScenario.situation_summary}
                    </p>
                  </div>

                  {/* Opening Line */}
                  <div className="bg-amber/5 border border-amber/20 rounded-md p-4">
                    <span className="font-mono text-[10px] text-amber tracking-wider uppercase">Customer Opening Line</span>
                    <p className="text-sm mt-2 italic text-foreground leading-relaxed">
                      "{generatedScenario.opening_line}"
                    </p>
                  </div>

                  {/* Persona Details */}
                  <div className="grid grid-cols-2 gap-3">
                    <div className="bg-secondary/30 rounded-md p-3 border border-border/50">
                      <span className="font-mono text-[10px] text-muted-foreground tracking-wider uppercase">Style</span>
                      <p className="text-xs mt-1">{generatedScenario.customer_persona.communication_style}</p>
                    </div>
                    <div className="bg-secondary/30 rounded-md p-3 border border-border/50">
                      <span className="font-mono text-[10px] text-muted-foreground tracking-wider uppercase">Initial Emotion</span>
                      <p className="text-xs mt-1 capitalize">{generatedScenario.customer_persona.initial_emotion}</p>
                    </div>
                  </div>

                  {/* Must Handle Well / Required Behaviors */}
                  <div>
                    <span className="font-mono text-[10px] text-teal tracking-wider uppercase">Required Behaviors</span>
                    <div className="mt-2 space-y-1.5">
                      {(generatedScenario.required_behaviors || generatedScenario.must_handle_well || []).map((item, i) => (
                        <div key={i} className="flex items-start gap-2 text-xs text-muted-foreground">
                          <span className="text-teal font-mono mt-0.5">{String(i + 1).padStart(2, '0')}</span>
                          <span>{item}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Launch Button */}
                  <Button
                    onClick={handleLaunch}
                    className="w-full bg-teal text-slate-deep hover:bg-teal/90 font-semibold gap-2"
                    size="lg"
                  >
                    Launch Simulation
                    <ArrowRight className="w-4 h-4" />
                  </Button>
                </div>
              )}
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
}
