export const ENV = {
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  vercelEnv: process.env.VERCEL_ENV ?? "",
  supabaseUrl: process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? "",
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? process.env.VITE_SUPABASE_ANON_KEY ?? "",
  supabasePublishableKey: process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  supabaseSessionMediaBucket: process.env.SUPABASE_SESSION_MEDIA_BUCKET ?? "session-media",
  supabasePolicyDocumentsBucket: process.env.SUPABASE_POLICY_DOCUMENTS_BUCKET ?? "policy-documents",
  supabaseGeneratedAssetsBucket: process.env.SUPABASE_GENERATED_ASSETS_BUCKET ?? "generated-assets",
  seedUserPassword: process.env.SUPABASE_SEED_PASSWORD ?? "WSCTraining123!",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  realtimeModel: process.env.REALTIME_MODEL ?? "gpt-realtime",
  realtimeVoice: process.env.REALTIME_VOICE ?? "alloy",
};
