export const ENV = {
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  vercelEnv: process.env.VERCEL_ENV ?? "",
  supabaseUrl: process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? "",
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? process.env.VITE_SUPABASE_ANON_KEY ?? "",
  supabasePublishableKey: process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  supabaseSessionMediaBucket: process.env.SUPABASE_SESSION_MEDIA_BUCKET ?? "session-media",
  supabasePolicyDocumentsBucket: process.env.SUPABASE_POLICY_DOCUMENTS_BUCKET ?? "policy-documents",
  supabaseGeneratedAssetsBucket: process.env.SUPABASE_GENERATED_ASSETS_BUCKET ?? "generated-assets",
  seedUserPassword: process.env.SUPABASE_SEED_PASSWORD ?? "WSCTraining123!",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  openaiApiKey: process.env.OPENAI_API_KEY ?? process.env.BUILT_IN_FORGE_API_KEY ?? "",
  llmModel: process.env.LLM_MODEL ?? process.env.OPENAI_LLM_MODEL ?? "",
  openaiSpeechBaseUrl: process.env.OPENAI_SPEECH_BASE_URL ?? process.env.BUILT_IN_FORGE_API_URL ?? "https://api.openai.com/v1",
  openaiSpeechModel: process.env.OPENAI_SPEECH_MODEL ?? "gpt-4o-mini-tts",
  realtimeModel: process.env.REALTIME_MODEL ?? "gpt-realtime",
  realtimeVoice: process.env.REALTIME_VOICE ?? "alloy",
  voiceRenderMode: process.env.VOICE_RENDER_MODE ?? "external-provider",
  voiceRenderPrimaryProvider: process.env.VOICE_RENDER_PRIMARY_PROVIDER ?? "cartesia",
  voiceRenderFallbackProviders: process.env.VOICE_RENDER_FALLBACK_PROVIDERS ?? "openai-native-speech,browser-native-speech",
  voiceRenderQaBaselineProvider: process.env.VOICE_RENDER_QA_BASELINE_PROVIDER ?? "openai-native-speech",
  voiceRenderAllowBrowserNativeFallback: process.env.VOICE_RENDER_ALLOW_BROWSER_NATIVE_FALLBACK === "true",
  liveVoiceAllowLocalBrowserFallback: process.env.LIVE_VOICE_ALLOW_LOCAL_BROWSER_FALLBACK === "true",
  cartesiaApiKey: process.env.CARTESIA_API_KEY ?? "",
  cartesiaBaseUrl: process.env.CARTESIA_BASE_URL ?? "https://api.cartesia.ai",
  cartesiaVersion: process.env.CARTESIA_VERSION ?? "2025-04-16",
  cartesiaModel: process.env.CARTESIA_MODEL ?? "sonic-3",
  elevenLabsApiKey: process.env.ELEVENLABS_API_KEY ?? "",
  elevenLabsBaseUrl: process.env.ELEVENLABS_BASE_URL ?? "https://api.elevenlabs.io/v1",
};
