/**
 * JSON schemas for structured LLM responses — all 10 prompts.
 */

export const scenarioDirectorSchema = {
  type: "json_schema" as const,
  json_schema: {
    name: "scenario_director",
    strict: true,
    schema: {
      type: "object",
      properties: {
        scenario_id: { type: "string" },
        department: { type: "string" },
        employee_role: { type: "string" },
        difficulty: { type: "integer" },
        scenario_family: { type: "string" },
        customer_persona: {
          type: "object",
          properties: {
            name: { type: "string" },
            age_band: { type: "string" },
            membership_context: { type: "string" },
            communication_style: { type: "string" },
            initial_emotion: { type: "string" },
            patience_level: { type: "string" },
            voice_hint: {
              type: "object",
              properties: {
                presentation: { type: "string", enum: ["feminine", "masculine", "neutral"] },
                locale: { type: "string" },
                age_flavor: { type: "string", enum: ["young_adult", "adult", "older_adult"] },
                notes: { type: "string" },
              },
              required: [],
              additionalProperties: false,
            },
          },
          required: ["name", "age_band", "membership_context", "communication_style", "initial_emotion", "patience_level"],
          additionalProperties: false,
        },
        situation_summary: { type: "string" },
        opening_line: { type: "string" },
        repeat_caller_key: { type: "string" },
        preserve_caller_voice: { type: "boolean" },
        hidden_facts: { type: "array", items: { type: "string" } },
        motive: { type: "string" },
        hidden_context: { type: "string" },
        personality_style: { type: "string" },
        past_history: { type: "string" },
        pressure_context: { type: "string" },
        friction_points: { type: "array", items: { type: "string" } },
        emotional_triggers: { type: "array", items: { type: "string" } },
        likely_assumptions: { type: "array", items: { type: "string" } },
        what_hearing_them_out_sounds_like: { type: "array", items: { type: "string" } },
        credible_next_steps: { type: "array", items: { type: "string" } },
        calm_down_if: { type: "array", items: { type: "string" } },
        lose_trust_if: { type: "array", items: { type: "string" } },
        approved_resolution_paths: { type: "array", items: { type: "string" } },
        required_behaviors: { type: "array", items: { type: "string" } },
        critical_errors: { type: "array", items: { type: "string" } },
        branch_logic: {
          type: "object",
          properties: {
            if_empathy_is_strong: { type: "string" },
            if_answer_is_vague: { type: "string" },
            if_policy_is_wrong: { type: "string" },
            if_employee_takes_ownership: { type: "string" },
            if_employee_fails_to_help: { type: "string" },
            if_employee_escalates_correctly: { type: "string" },
          },
          required: ["if_empathy_is_strong", "if_answer_is_vague", "if_policy_is_wrong", "if_employee_takes_ownership", "if_employee_fails_to_help", "if_employee_escalates_correctly"],
          additionalProperties: false,
        },
        emotion_progression: {
          type: "object",
          properties: {
            starting_state: { type: "string" },
            better_if: { type: "array", items: { type: "string" } },
            worse_if: { type: "array", items: { type: "string" } },
          },
          required: ["starting_state", "better_if", "worse_if"],
          additionalProperties: false,
        },
        completion_rules: {
          type: "object",
          properties: {
            resolved_if: { type: "array", items: { type: "string" } },
            end_early_if: { type: "array", items: { type: "string" } },
            manager_required_if: { type: "array", items: { type: "string" } },
          },
          required: ["resolved_if", "end_early_if", "manager_required_if"],
          additionalProperties: false,
        },
        completion_criteria: { type: "array", items: { type: "string" } },
        failure_criteria: { type: "array", items: { type: "string" } },
        recommended_turns: { type: "integer" },
      },
      required: [
        "scenario_id", "department", "employee_role", "difficulty", "scenario_family",
        "customer_persona", "situation_summary", "opening_line", "hidden_facts",
        "approved_resolution_paths", "required_behaviors", "critical_errors",
        "branch_logic", "emotion_progression", "completion_rules", "recommended_turns"
      ],
      additionalProperties: false,
    },
  },
};

export const customerReplySchema = {
  type: "json_schema" as const,
  json_schema: {
    name: "customer_reply",
    strict: true,
    schema: {
      type: "object",
      properties: {
        customer_reply: { type: "string" },
        updated_emotion: { type: "string" },
        trust_level: { type: "integer" },
        issue_clarity: { type: "integer" },
        manager_needed: { type: "boolean" },
        scenario_complete: { type: "boolean" },
        completion_reason: { type: "string" },
        new_hidden_fact_revealed: { type: "string" },
        director_notes: {
          type: "object",
          properties: {
            employee_showed_empathy: { type: "boolean" },
            employee_was_clear: { type: "boolean" },
            employee_used_correct_policy: { type: "boolean" },
            employee_took_ownership: { type: "boolean" },
            employee_should_be_pushed_harder: { type: "boolean" },
          },
          required: ["employee_showed_empathy", "employee_was_clear", "employee_used_correct_policy", "employee_took_ownership", "employee_should_be_pushed_harder"],
          additionalProperties: false,
        },
      },
      required: ["customer_reply", "updated_emotion", "trust_level", "issue_clarity", "manager_needed", "scenario_complete", "completion_reason", "new_hidden_fact_revealed", "director_notes"],
      additionalProperties: false,
    },
  },
};

export const stateManagerSchema = {
  type: "json_schema" as const,
  json_schema: {
    name: "conversation_state",
    strict: true,
    schema: {
      type: "object",
      properties: {
        turn_number: { type: "integer" },
        emotion_state: { type: "string" },
        emotional_state: { type: "string" },
        trust_level: { type: "integer" },
        issue_clarity: { type: "integer" },
        issue_complexity: { type: "integer" },
        clarification_depth: { type: "integer" },
        trust_damage_count: { type: "integer" },
        trust_recovery_count: { type: "integer" },
        unresolved_gap_count: { type: "integer" },
        misunderstood_turn_count: { type: "integer" },
        follow_up_question_count: { type: "integer" },
        resolution_momentum: { type: "integer" },
        no_progress_turns: { type: "integer" },
        stall_failure_risk: { type: "integer" },
        pacing_summary: { type: "string" },
        initial_customer_complaint: { type: "string" },
        complaint_category: { type: "string" },
        complaint_status: { type: "string", enum: ["OPEN", "PARTIALLY_ADDRESSED", "REDIRECT_PENDING", "RESOLVED", "ESCALATED", "ABANDONED"] },
        complaint_still_open: { type: "boolean" },
        current_customer_goal: { type: "string" },
        customer_belief_about_problem: { type: "string" },
        true_underlying_problem: { type: "string" },
        root_issue_status: { type: "string", enum: ["UNRESOLVED", "PARTIALLY_ADDRESSED", "REDIRECT_PENDING", "RESOLVED", "ABANDONED"] },
        subissues_open: { type: "array", items: { type: "string" } },
        discovered_facts: { type: "array", items: { type: "string" } },
        false_customer_assumptions: { type: "array", items: { type: "string" } },
        confirmed_business_facts: { type: "array", items: { type: "string" } },
        resolution_requirements: { type: "array", items: { type: "string" } },
        next_step_requirements: { type: "array", items: { type: "string" } },
        escalation_requirements: { type: "array", items: { type: "string" } },
        unresolved_subissues: { type: "array", items: { type: "string" } },
        employee_promises_made: { type: "array", items: { type: "string" } },
        employee_flags: {
          type: "object",
          properties: {
            showed_empathy: { type: "boolean" },
            answered_directly: { type: "boolean" },
            used_correct_policy: { type: "boolean" },
            took_ownership: { type: "boolean" },
            avoided_question: { type: "boolean" },
            critical_error: { type: "boolean" },
          },
          required: ["showed_empathy", "answered_directly", "used_correct_policy", "took_ownership", "avoided_question", "critical_error"],
          additionalProperties: false,
        },
        escalation_required: { type: "boolean" },
        scenario_risk_level: { type: "string" },
        continue_simulation: { type: "boolean" },
        customer_goal: { type: "string" },
        goal_status: { type: "string", enum: ["ACTIVE", "PARTIALLY_RESOLVED", "RESOLVED", "ESCALATED", "ABANDONED", "TIMED_OUT"] },
        issue_progress_state: { type: "string", enum: ["ACTIVE", "PARTIALLY_RESOLVED", "RESOLVED", "ESCALATED", "ABANDONED", "TIMED_OUT"] },
        terminal_outcome_state: { type: "string", enum: ["ACTIVE", "PARTIALLY_RESOLVED", "RESOLVED", "ESCALATED", "ABANDONED", "TIMED_OUT"] },
        terminal_validation_reason: { type: "string" },
        completion_blockers: { type: "array", items: { type: "string" } },
        accepted_next_step: { type: "boolean" },
        next_step_owner: { type: "string" },
        next_step_action: { type: "string" },
        next_step_timeline: { type: "string" },
        next_step_missing_fields: { type: "array", items: { type: "string" } },
        valid_redirect: { type: "boolean" },
        escalation_validity: { type: "string", enum: ["invalid", "potential", "valid"] },
        premature_closure_detected: { type: "boolean" },
        unmet_completion_criteria: { type: "array", items: { type: "string" } },
        unresolved_customer_questions: { type: "array", items: { type: "string" } },
        unresolved_questions: { type: "array", items: { type: "string" } },
        outcome_summary: { type: "string" },
        patience_level: { type: "integer" },
        urgency_level: { type: "integer" },
        communication_style: { type: "string" },
        cooperation_level: { type: "integer" },
        offense_level: { type: "integer" },
        manager_request_level: { type: "integer" },
        resolution_confidence: { type: "integer" },
        confidence_in_employee: { type: "integer" },
        willingness_to_accept_redirect: { type: "integer" },
        willingness_to_escalate: { type: "integer" },
        customer_strategy: {
          type: "string",
          enum: [
            "seek_acknowledgment",
            "seek_clarity",
            "seek_action",
            "seek_reassurance",
            "protect_dignity",
            "press_for_specifics",
            "request_manager",
            "follow_direction",
            "close_out",
          ],
        },
        likely_next_behavior: {
          type: "string",
          enum: [
            "stay_engaged",
            "ask_follow_up",
            "become_cautious",
            "become_defensive",
            "request_manager",
            "disengage",
            "follow_instructions",
            "close_conversation",
          ],
        },
        emotional_shift_explanation: { type: "string" },
        conversation_stage: {
          type: "string",
          enum: ["opening", "fact_finding", "resolution", "escalation", "closure"],
        },
        analysis_summary: { type: "string" },
        runtime_events: {
          type: "array",
          items: {
            type: "object",
            properties: {
              type: {
                type: "string",
                enum: [
                  "unresolved_complaint_persists",
                  "complaint_partially_addressed",
                  "complaint_fully_resolved",
                  "next_step_offered",
                  "next_step_rejected",
                  "escalation_offered",
                  "escalation_accepted",
                  "premature_closure_attempted",
                  "unresolved_gap_reopened",
                  "timeout_failure",
                  "abandonment_detected",
                ],
              },
              source: { type: "string", enum: ["state_manager", "client", "live_runtime", "persistence"] },
              atTurn: { type: "integer" },
              summary: { type: "string" },
          outcomeState: { type: "string", enum: ["ACTIVE", "PARTIALLY_RESOLVED", "RESOLVED", "ESCALATED", "ABANDONED", "TIMED_OUT"] },
              unmetCriteria: { type: "array", items: { type: "string" } },
              blockedBy: { type: "array", items: { type: "string" } },
              prematureClosure: {
                type: "object",
                properties: {
                  trigger_source: {
                    type: "string",
                    enum: [
                      "employee_transcript",
                      "employee_wrap_up_language",
                      "customer_reply_pattern",
                      "runtime_end_trigger",
                      "ui_auto_finish",
                      "transcript_finalized",
                    ],
                  },
                  trigger_phrase_or_reason: { type: "string" },
                  complaint_still_open: { type: "boolean" },
                  unresolved_gaps_snapshot: { type: "array", items: { type: "string" } },
                  trust_level_at_attempt: { type: ["number", "null"] },
                  emotional_state_at_attempt: { type: ["string", "null"] },
                  blocked: { type: "boolean" },
                  customer_strategy_at_attempt: { type: ["string", "null"] },
                  likely_next_behavior_at_attempt: { type: ["string", "null"] },
                },
                required: [
                  "trigger_source",
                  "trigger_phrase_or_reason",
                  "complaint_still_open",
                  "unresolved_gaps_snapshot",
                  "trust_level_at_attempt",
                  "emotional_state_at_attempt",
                  "blocked",
                ],
                additionalProperties: false,
              },
            },
            required: ["type", "source", "atTurn", "summary", "unmetCriteria", "blockedBy"],
            additionalProperties: false,
          },
        },
        latest_employee_analysis: {
          type: "object",
          properties: {
            clarity: { type: "integer" },
            politeness: { type: "integer" },
            warmth: { type: "integer" },
            confidence: { type: "integer" },
            respectfulness: { type: "integer" },
            empathy: { type: "integer" },
            professionalism: { type: "integer" },
            helpfulness: { type: "integer" },
            accuracy: { type: "integer" },
            accuracyConfidence: { type: "integer" },
            ownership: { type: "integer" },
            directness: { type: "integer" },
            explanationQuality: { type: "integer" },
            nextStepQuality: { type: "integer" },
            respectImpact: { type: "integer" },
            heardImpact: { type: "integer" },
            escalationJudgment: { type: "integer" },
            toneLabels: { type: "array", items: { type: "string" } },
            strengths: { type: "array", items: { type: "string" } },
            issues: { type: "array", items: { type: "string" } },
            serviceSummary: { type: "string" },
            answeredQuestion: { type: "boolean" },
            avoidedQuestion: { type: "boolean" },
            soundedDismissive: { type: "boolean" },
            soundedRude: { type: "boolean" },
            setExpectationsClearly: { type: "boolean" },
            tookOwnership: { type: "boolean" },
            escalatedAppropriately: { type: "boolean" },
            madeCustomerFeelHeard: { type: "boolean" },
            contradictionDetected: { type: "boolean" },
            vaguenessDetected: { type: "boolean" },
            fakeConfidence: { type: "boolean" },
            blameShifting: { type: "boolean" },
            policyMisuse: { type: "boolean" },
            overTalking: { type: "boolean" },
            deadEndLanguage: { type: "boolean" },
            disrespect: { type: "boolean" },
            passiveAggression: { type: "boolean" },
            roboticPhrasing: { type: "boolean" },
            explicitManagerMention: { type: "boolean" },
            explicitDisrespect: { type: "boolean" },
            explicitOwnership: { type: "boolean" },
            explicitNextStep: { type: "boolean" },
            explicitTimeline: { type: "boolean" },
            explicitVerification: { type: "boolean" },
            explicitExplanation: { type: "boolean" },
            explicitSafetyControl: { type: "boolean" },
            explicitDirection: { type: "boolean" },
            explicitDiscovery: { type: "boolean" },
            explicitRecommendation: { type: "boolean" },
            explicitClosureAttempt: { type: "boolean" },
            likelySolved: { type: "boolean" },
            likelyStalled: { type: "boolean" },
            summary: { type: "string" },
          },
          required: [
            "clarity",
            "politeness",
            "warmth",
            "confidence",
            "respectfulness",
            "empathy",
            "professionalism",
            "helpfulness",
            "accuracy",
            "accuracyConfidence",
            "ownership",
            "directness",
            "explanationQuality",
            "nextStepQuality",
            "respectImpact",
            "heardImpact",
            "escalationJudgment",
            "toneLabels",
            "strengths",
            "issues",
            "serviceSummary",
            "answeredQuestion",
            "avoidedQuestion",
            "soundedDismissive",
            "soundedRude",
            "setExpectationsClearly",
            "tookOwnership",
            "escalatedAppropriately",
            "madeCustomerFeelHeard",
            "contradictionDetected",
            "vaguenessDetected",
            "fakeConfidence",
            "blameShifting",
            "policyMisuse",
            "overTalking",
            "deadEndLanguage",
            "disrespect",
            "passiveAggression",
            "roboticPhrasing",
            "explicitManagerMention",
            "explicitDisrespect",
            "explicitOwnership",
            "explicitNextStep",
            "explicitTimeline",
            "explicitVerification",
            "explicitExplanation",
            "explicitSafetyControl",
            "explicitDirection",
            "explicitDiscovery",
            "explicitRecommendation",
            "explicitClosureAttempt",
            "likelySolved",
            "likelyStalled",
            "summary",
          ],
          additionalProperties: false,
        },
      },
      required: [
        "turn_number",
        "emotion_state",
        "emotional_state",
        "trust_level",
        "issue_clarity",
        "issue_complexity",
        "clarification_depth",
        "trust_damage_count",
        "trust_recovery_count",
        "unresolved_gap_count",
        "misunderstood_turn_count",
        "follow_up_question_count",
        "resolution_momentum",
        "no_progress_turns",
        "stall_failure_risk",
        "pacing_summary",
        "initial_customer_complaint",
        "complaint_category",
        "complaint_status",
        "complaint_still_open",
        "customer_belief_about_problem",
        "true_underlying_problem",
        "subissues_open",
        "discovered_facts",
        "false_customer_assumptions",
        "confirmed_business_facts",
        "resolution_requirements",
        "next_step_requirements",
        "escalation_requirements",
        "unresolved_subissues",
        "employee_promises_made",
        "employee_flags",
        "escalation_required",
        "scenario_risk_level",
        "continue_simulation",
        "customer_goal",
        "goal_status",
        "issue_progress_state",
        "terminal_outcome_state",
        "terminal_validation_reason",
        "completion_blockers",
        "accepted_next_step",
        "next_step_owner",
        "next_step_action",
        "next_step_timeline",
        "next_step_missing_fields",
        "valid_redirect",
        "premature_closure_detected",
        "unmet_completion_criteria",
        "unresolved_customer_questions",
        "unresolved_questions",
        "outcome_summary",
        "patience_level",
        "urgency_level",
        "communication_style",
        "cooperation_level",
        "offense_level",
        "manager_request_level",
        "resolution_confidence",
        "confidence_in_employee",
        "willingness_to_accept_redirect",
        "willingness_to_escalate",
        "customer_strategy",
        "likely_next_behavior",
        "emotional_shift_explanation",
        "conversation_stage",
        "analysis_summary",
        "runtime_events",
        "latest_employee_analysis",
      ],
      additionalProperties: false,
    },
  },
};

export const policyGroundingSchema = {
  type: "json_schema" as const,
  json_schema: {
    name: "policy_grounding",
    strict: true,
    schema: {
      type: "object",
      properties: {
        policy_accuracy: { type: "string" },
        matched_policy_points: { type: "array", items: { type: "string" } },
        missed_policy_points: { type: "array", items: { type: "string" } },
        invented_or_risky_statements: { type: "array", items: { type: "string" } },
        should_have_escalated: { type: "boolean" },
        policy_notes: { type: "string" },
      },
      required: ["policy_accuracy", "matched_policy_points", "missed_policy_points", "invented_or_risky_statements", "should_have_escalated", "policy_notes"],
      additionalProperties: false,
    },
  },
};

export const evaluatorSchema = {
  type: "json_schema" as const,
  json_schema: {
    name: "evaluation_result",
    strict: true,
    schema: {
      type: "object",
      properties: {
        overall_score: { type: "integer" },
        pass_fail: { type: "string" },
        readiness_signal: { type: "string" },
        category_scores: {
          type: "object",
          properties: {
            opening_warmth: { type: "integer" },
            listening_empathy: { type: "integer" },
            clarity_directness: { type: "integer" },
            policy_accuracy: { type: "integer" },
            ownership: { type: "integer" },
            problem_solving: { type: "integer" },
            de_escalation: { type: "integer" },
            escalation_judgment: { type: "integer" },
            visible_professionalism: { type: "integer" },
            closing_control: { type: "integer" },
          },
          required: [
            "opening_warmth", "listening_empathy", "clarity_directness",
            "policy_accuracy", "ownership", "problem_solving",
            "de_escalation", "escalation_judgment",
            "visible_professionalism", "closing_control"
          ],
          additionalProperties: false,
        },
        score_dimensions: {
          type: "object",
          properties: {
            interaction_quality: { type: "integer" },
            operational_effectiveness: { type: "integer" },
            outcome_quality: { type: "integer" },
          },
          required: ["interaction_quality", "operational_effectiveness", "outcome_quality"],
          additionalProperties: false,
        },
        best_moments: { type: "array", items: { type: "string" } },
        missed_moments: { type: "array", items: { type: "string" } },
        critical_mistakes: { type: "array", items: { type: "string" } },
        coachable_mistakes: { type: "array", items: { type: "string" } },
        most_important_correction: { type: "string" },
        ideal_response_example: { type: "string" },
        summary: { type: "string" },
      },
      required: [
        "overall_score", "pass_fail", "readiness_signal", "category_scores", "score_dimensions",
        "best_moments", "missed_moments", "critical_mistakes", "coachable_mistakes",
        "most_important_correction", "ideal_response_example", "summary"
      ],
      additionalProperties: false,
    },
  },
};

export const employeeCoachSchema = {
  type: "json_schema" as const,
  json_schema: {
    name: "employee_coaching",
    strict: true,
    schema: {
      type: "object",
      properties: {
        employee_coaching_summary: { type: "string" },
        what_you_did_well: { type: "array", items: { type: "string" } },
        what_hurt_you: { type: "array", items: { type: "string" } },
        do_this_next_time: { type: "array", items: { type: "string" } },
        replacement_phrases: { type: "array", items: { type: "string" } },
        practice_focus: { type: "string" },
        next_recommended_scenario: { type: "string" },
      },
      required: ["employee_coaching_summary", "what_you_did_well", "what_hurt_you", "do_this_next_time", "replacement_phrases", "practice_focus", "next_recommended_scenario"],
      additionalProperties: false,
    },
  },
};

export const managerDebriefSchema = {
  type: "json_schema" as const,
  json_schema: {
    name: "manager_debrief",
    strict: true,
    schema: {
      type: "object",
      properties: {
        manager_summary: { type: "string" },
        performance_signal: { type: "string" },
        top_strengths: { type: "array", items: { type: "string" } },
        top_corrections: { type: "array", items: { type: "string" } },
        whether_live_shadowing_is_needed: { type: "boolean" },
        whether_manager_follow_up_is_needed: { type: "boolean" },
        recommended_follow_up_action: { type: "string" },
        recommended_next_drill: { type: "string" },
      },
      required: ["manager_summary", "performance_signal", "top_strengths", "top_corrections", "whether_live_shadowing_is_needed", "whether_manager_follow_up_is_needed", "recommended_follow_up_action", "recommended_next_drill"],
      additionalProperties: false,
    },
  },
};

export const adaptiveDifficultySchema = {
  type: "json_schema" as const,
  json_schema: {
    name: "adaptive_difficulty",
    strict: true,
    schema: {
      type: "object",
      properties: {
        next_difficulty: { type: "integer" },
        difficulty_reason: { type: "string" },
        recommended_scenario_family: { type: "string" },
        recommended_emotional_intensity: { type: "string" },
        recommended_complexity: { type: "string" },
      },
      required: ["next_difficulty", "difficulty_reason", "recommended_scenario_family", "recommended_emotional_intensity", "recommended_complexity"],
      additionalProperties: false,
    },
  },
};

export const sessionQualitySchema = {
  type: "json_schema" as const,
  json_schema: {
    name: "session_quality",
    strict: true,
    schema: {
      type: "object",
      properties: {
        session_quality: { type: "string" },
        flags: { type: "array", items: { type: "string" } },
        reason: { type: "string" },
        retry_recommended: { type: "boolean" },
      },
      required: ["session_quality", "flags", "reason", "retry_recommended"],
      additionalProperties: false,
    },
  },
};

export const profileUpdateSchema = {
  type: "json_schema" as const,
  json_schema: {
    name: "profile_update",
    strict: true,
    schema: {
      type: "object",
      properties: {
        level_estimate: { type: "string" },
        readiness_status: { type: "string" },
        trend: { type: "string" },
        skill_map: {
          type: "object",
          properties: {
            empathy: { type: "integer" },
            clarity: { type: "integer" },
            policy_accuracy: { type: "integer" },
            ownership: { type: "integer" },
            de_escalation: { type: "integer" },
            escalation_judgment: { type: "integer" },
            professional_presence: { type: "integer" },
          },
          required: ["empathy", "clarity", "policy_accuracy", "ownership", "de_escalation", "escalation_judgment", "professional_presence"],
          additionalProperties: false,
        },
        strongest_scenario_families: { type: "array", items: { type: "string" } },
        weakest_scenario_families: { type: "array", items: { type: "string" } },
        pressure_handling: { type: "string" },
        consistency_score: { type: "integer" },
        recommended_next_steps: { type: "array", items: { type: "string" } },
        manager_attention_flag: { type: "boolean" },
      },
      required: [
        "level_estimate", "readiness_status", "trend", "skill_map",
        "strongest_scenario_families", "weakest_scenario_families",
        "pressure_handling", "consistency_score", "recommended_next_steps",
        "manager_attention_flag"
      ],
      additionalProperties: false,
    },
  },
};
