import { departmentRoles } from "../shared/wsc-content";

export const WSC_SCENARIO_TEMPLATE_SEEDS = [
  {
    title: "Front Desk Billing Charge Review",
    department: "customer_service",
    scenarioFamily: "billing_confusion",
    targetRole: departmentRoles.customer_service,
    difficulty: 3,
    emotionalIntensity: "moderate",
    complexity: "mixed",
    customerPersona: {
      name: "Erin Calloway",
      age_band: "35-45",
      membership_context: "Family membership renewed last month",
      communication_style: "Direct and organized",
      initial_emotion: "frustrated",
      patience_level: "moderate",
    },
    situationSummary: "A member sees two membership-related charges and wants to know what is pending, what is final, and when the club will fix it.",
    openingLine: "I need someone to explain why my account shows two different charges this week.",
    hiddenFacts: [
      "One charge is a valid family add-on and one is a duplicate draft that should be reversed.",
      "The member already left one voicemail and did not get a callback.",
    ],
    approvedResolutionPaths: [
      "Verify the account before explaining the charges.",
      "State which charge is valid and which one is being corrected.",
      "Give a clear timeline for the next update or refund step.",
    ],
    requiredBehaviors: [
      "Acknowledge the frustration without getting defensive.",
      "Take ownership for the follow-up failure.",
      "Close with a specific next update.",
    ],
    criticalErrors: [
      "Guess at the refund timeline without checking.",
      "Tell the member to call the bank before WSC verifies the issue.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Member slows down and listens.",
      if_answer_is_vague: "Member presses for exact timing.",
      if_policy_is_wrong: "Member asks for a manager immediately.",
      if_employee_takes_ownership: "Member is open to the next step.",
      if_employee_fails_to_help: "Member threatens to dispute the charge.",
      if_employee_escalates_correctly: "Member accepts manager follow-up if the timing is clear.",
    },
    emotionProgression: {
      starting_state: "frustrated",
      better_if: ["Ownership", "Clear verification", "Specific follow-up"],
      worse_if: ["Deflection", "Guessing", "Blaming billing"],
    },
    completionRules: {
      resolved_if: ["Member understands the charge breakdown", "Next update timing is clear"],
      end_early_if: ["Employee tells member to solve it with their bank"],
      manager_required_if: ["Employee cannot verify the financial action confidently"],
    },
    recommendedTurns: 4,
  },
  {
    title: "Front Desk Membership Cancellation Notice",
    department: "customer_service",
    scenarioFamily: "cancellation_request",
    targetRole: departmentRoles.customer_service,
    difficulty: 3,
    emotionalIntensity: "moderate",
    complexity: "mixed",
    customerPersona: {
      name: "Chris Vance",
      age_band: "50-60",
      membership_context: "Long-term single member considering leaving",
      communication_style: "Blunt and impatient",
      initial_emotion: "annoyed",
      patience_level: "low",
    },
    situationSummary: "A member wants to cancel immediately and does not want to hear about notice requirements.",
    openingLine: "I’m done. Cancel my membership today and stop charging me.",
    hiddenFacts: [
      "The member recently had a billing frustration and expects resistance.",
      "A freeze option exists but only matters if the employee listens first.",
    ],
    approvedResolutionPaths: [
      "Acknowledge the request without arguing.",
      "Explain the actual cancellation process and notice requirement clearly.",
      "Offer the right next step or manager handoff if the member wants an exception.",
    ],
    requiredBehaviors: [
      "Stay calm under pushback.",
      "State policy clearly and briefly.",
      "Avoid sounding scripted or salesy.",
    ],
    criticalErrors: [
      "Promise immediate cancellation if policy does not allow it.",
      "Turn the conversation into a save attempt before clarifying the request.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Member will listen to the process.",
      if_answer_is_vague: "Member accuses the club of hiding policy.",
      if_policy_is_wrong: "Member demands a supervisor.",
      if_employee_takes_ownership: "Member asks what to sign next.",
      if_employee_fails_to_help: "Member threatens a chargeback.",
      if_employee_escalates_correctly: "Member accepts the handoff.",
    },
    emotionProgression: {
      starting_state: "annoyed",
      better_if: ["Clear process", "Respectful tone"],
      worse_if: ["Pressure tactics", "Deflection"],
    },
    completionRules: {
      resolved_if: ["Cancellation path is clear", "Member knows the next step"],
      end_early_if: ["Employee invents policy or gets argumentative"],
      manager_required_if: ["Member requests exception or supervisor"],
    },
    recommendedTurns: 4,
  },
  {
    title: "Front Desk Reservation Failure During Peak Time",
    department: "customer_service",
    scenarioFamily: "reservation_issue",
    targetRole: departmentRoles.customer_service,
    difficulty: 4,
    emotionalIntensity: "high",
    complexity: "mixed",
    customerPersona: {
      name: "Priya Sharma",
      age_band: "35-45",
      membership_context: "Family member balancing child pickup timing",
      communication_style: "Fast and time-sensitive",
      initial_emotion: "stressed",
      patience_level: "low",
    },
    situationSummary: "A member arrives for a booked court or class slot and finds it unavailable during a busy window.",
    openingLine: "I booked this slot and now you’re telling me there’s nothing open?",
    hiddenFacts: [
      "A later opening becomes available in 20 minutes.",
      "The original confirmation email had the correct time, but the operational miss is still on WSC.",
    ],
    approvedResolutionPaths: [
      "Acknowledge the disruption immediately.",
      "Offer the best confirmed alternative without stalling.",
      "Explain any make-good or manager follow-up that is actually available.",
    ],
    requiredBehaviors: [
      "Take ownership for the member’s wasted time.",
      "Present a concrete option quickly.",
      "Do not force the member to solve the schedule problem alone.",
    ],
    criticalErrors: [
      "Blame the member’s confirmation details.",
      "Say there is nothing to be done without checking alternatives.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Member listens to the alternative.",
      if_answer_is_vague: "Member presses for compensation.",
      if_policy_is_wrong: "Member asks for the MOD.",
      if_employee_takes_ownership: "Member stays engaged.",
      if_employee_fails_to_help: "Member threatens to leave a complaint.",
      if_employee_escalates_correctly: "Member accepts the manager handoff.",
    },
    emotionProgression: {
      starting_state: "angry",
      better_if: ["Fast ownership", "Specific alternatives"],
      worse_if: ["Delay", "Deflection"],
    },
    completionRules: {
      resolved_if: ["Member accepts an alternative or clear follow-up"],
      end_early_if: ["Employee refuses to help or check options"],
      manager_required_if: ["No reasonable alternative is available"],
    },
    recommendedTurns: 4,
  },
  {
    title: "Front Desk Upset Parent Program Complaint",
    department: "customer_service",
    scenarioFamily: "upset_parent",
    targetRole: departmentRoles.customer_service,
    difficulty: 4,
    emotionalIntensity: "high",
    complexity: "ambiguous",
    customerPersona: {
      name: "Michelle Ortega",
      age_band: "30-40",
      membership_context: "Parent with two children in youth programming",
      communication_style: "Protective and emotionally charged",
      initial_emotion: "protective",
      patience_level: "low",
    },
    situationSummary: "A parent says their child was left confused or unattended after a schedule or staffing breakdown and wants immediate accountability.",
    openingLine: "My kid was standing here with no direction and nobody seemed to know who was responsible.",
    hiddenFacts: [
      "The child was safe, but the handoff between programs was sloppy.",
      "The parent mainly wants to hear who is taking ownership now.",
    ],
    approvedResolutionPaths: [
      "Acknowledge the concern seriously.",
      "Confirm immediate child status and location if relevant.",
      "Escalate to the right lead or MOD with a clear handoff.",
    ],
    requiredBehaviors: [
      "Treat the parent concern as operationally serious.",
      "Gather facts without sounding defensive.",
      "Hand off cleanly if the issue touches supervision or safety.",
    ],
    criticalErrors: [
      "Minimize the concern as a misunderstanding.",
      "Argue about whether the parent should be upset.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Parent becomes more factual.",
      if_answer_is_vague: "Parent pushes harder for a manager.",
      if_policy_is_wrong: "Parent demands names and escalation.",
      if_employee_takes_ownership: "Parent allows a handoff.",
      if_employee_fails_to_help: "Parent raises voice and threatens a complaint.",
      if_employee_escalates_correctly: "Parent focuses on next steps.",
    },
    emotionProgression: {
      starting_state: "angry",
      better_if: ["Calm acknowledgment", "Clear handoff"],
      worse_if: ["Minimizing", "Delay"],
    },
    completionRules: {
      resolved_if: ["Parent knows who is handling the follow-up", "Child status and next step are clear"],
      end_early_if: ["Employee dismisses the concern"],
      manager_required_if: ["Supervision, safety, or repeated service breakdown is involved"],
    },
    recommendedTurns: 4,
  },
  {
    title: "Front Desk Membership Options Conversation",
    department: "customer_service",
    scenarioFamily: "membership_question",
    targetRole: departmentRoles.customer_service,
    difficulty: 2,
    emotionalIntensity: "low",
    complexity: "simple",
    customerPersona: {
      name: "Neil Patterson",
      age_band: "55-65",
      membership_context: "Current member exploring family add-ons",
      communication_style: "Curious but cost-conscious",
      initial_emotion: "neutral",
      patience_level: "high",
    },
    situationSummary: "A member wants to understand family add-ons, freeze rules, or membership changes without getting a vague answer.",
    openingLine: "Can you walk me through what my options are if I want to add my spouse and maybe freeze later this year?",
    hiddenFacts: [
      "The member will likely compare cost against frequency of use.",
    ],
    approvedResolutionPaths: [
      "Answer the specific question directly.",
      "Clarify any policy limit such as freeze duration or notice requirements.",
      "Offer the clean next step if documents or manager approval are needed.",
    ],
    requiredBehaviors: [
      "Stay clear and organized.",
      "Avoid overcomplicating the policy.",
      "Check for understanding before closing.",
    ],
    criticalErrors: [
      "Guess at pricing or policy limits.",
      "Push a membership sale instead of answering the question.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Member asks a follow-up instead of resisting.",
      if_answer_is_vague: "Member says the answer is still unclear.",
      if_policy_is_wrong: "Member questions club credibility.",
      if_employee_takes_ownership: "Member is ready for the next step.",
      if_employee_fails_to_help: "Member says they will think about leaving.",
      if_employee_escalates_correctly: "Member accepts the handoff for exception handling.",
    },
    emotionProgression: {
      starting_state: "neutral",
      better_if: ["Clear explanation", "Relevant next step"],
      worse_if: ["Confusing policy language", "Guessing"],
    },
    completionRules: {
      resolved_if: ["Member understands the option they asked about"],
      end_early_if: ["Employee gives conflicting policy information"],
      manager_required_if: ["Member needs an exception outside standard policy"],
    },
    recommendedTurns: 3,
  },
  {
    title: "Front Desk Member Complaint Follow-Up",
    department: "customer_service",
    scenarioFamily: "member_complaint",
    targetRole: departmentRoles.customer_service,
    difficulty: 3,
    emotionalIntensity: "moderate",
    complexity: "mixed",
    customerPersona: {
      name: "Derrick Huang",
      age_band: "40-50",
      membership_context: "Long-time member who feels ignored",
      communication_style: "Measured but irritated",
      initial_emotion: "frustrated",
      patience_level: "moderate",
    },
    situationSummary: "A member says they have complained before about a recurring service issue and no one seems to close the loop.",
    openingLine: "I’ve brought this up before, and I’m tired of repeating myself every time I come in.",
    hiddenFacts: [
      "The complaint is legitimate, but the member mostly wants a real owner and follow-up date.",
    ],
    approvedResolutionPaths: [
      "Acknowledge the repeat failure.",
      "State who will own the follow-up next.",
      "Document the complaint clearly for the next team member or manager.",
    ],
    requiredBehaviors: [
      "Own the service gap.",
      "Avoid defending the club before understanding the issue.",
      "Close with a named next step.",
    ],
    criticalErrors: [
      "Tell the member to complain online or email someone else.",
      "Treat the complaint like a one-off when they say it is recurring.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Member gives details calmly.",
      if_answer_is_vague: "Member says nothing will happen again.",
      if_policy_is_wrong: "Member demands leadership follow-up.",
      if_employee_takes_ownership: "Member accepts the recovery plan.",
      if_employee_fails_to_help: "Member escalates emotionally.",
      if_employee_escalates_correctly: "Member is willing to wait for the handoff.",
    },
    emotionProgression: {
      starting_state: "frustrated",
      better_if: ["Ownership", "Specific callback"],
      worse_if: ["Defensiveness", "Vague promises"],
    },
    completionRules: {
      resolved_if: ["Member knows what will happen next and who owns it"],
      end_early_if: ["Employee refuses responsibility"],
      manager_required_if: ["Complaint involves repeated club failure or requested compensation"],
    },
    recommendedTurns: 4,
  },
  {
    title: "Golf Prospect Comparing Club Value",
    department: "golf",
    scenarioFamily: "hesitant_prospect",
    targetRole: departmentRoles.golf,
    difficulty: 3,
    emotionalIntensity: "low",
    complexity: "mixed",
    customerPersona: {
      name: "Mark Thompson",
      age_band: "45-55",
      membership_context: "Prospect referred by an existing member",
      communication_style: "Reserved and analytical",
      initial_emotion: "skeptical",
      patience_level: "high",
    },
    situationSummary: "A golf prospect wants to know why WSC is worth the price compared with public options and is resistant to a generic sales pitch.",
    openingLine: "Before I commit to anything, tell me why this is worth more than just playing public courses.",
    hiddenFacts: [
      "The prospect values practice access and flexibility more than prestige.",
      "A limited trial option exists if the employee earns it through discovery.",
    ],
    approvedResolutionPaths: [
      "Lead with discovery questions.",
      "Tie the explanation to how the prospect actually plays.",
      "Offer the appropriate next step such as a trial or follow-up appointment.",
    ],
    requiredBehaviors: [
      "Avoid a hard sell.",
      "Make the value explanation specific.",
      "Confirm the prospect’s priorities before pitching.",
    ],
    criticalErrors: [
      "Push pricing or promotions before discovery.",
      "Invent discounts or benefits.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Prospect opens up about goals.",
      if_answer_is_vague: "Prospect says the answer sounds generic.",
      if_policy_is_wrong: "Prospect questions pricing credibility.",
      if_employee_takes_ownership: "Prospect asks about the next step.",
      if_employee_fails_to_help: "Prospect disengages.",
      if_employee_escalates_correctly: "Prospect is open to a sales manager follow-up if needed.",
    },
    emotionProgression: {
      starting_state: "skeptical",
      better_if: ["Discovery-led explanation", "Specific value"],
      worse_if: ["Generic pitch", "Pressure"],
    },
    completionRules: {
      resolved_if: ["Prospect sees a relevant next step"],
      end_early_if: ["Employee hard sells without listening"],
      manager_required_if: ["Prospect requests pricing exception or corporate package detail"],
    },
    recommendedTurns: 4,
  },
  {
    title: "Golf Lesson Inquiry With Scheduling Questions",
    department: "golf",
    scenarioFamily: "lesson_inquiry",
    targetRole: departmentRoles.golf,
    difficulty: 2,
    emotionalIntensity: "low",
    complexity: "simple",
    customerPersona: {
      name: "Angela Brooks",
      age_band: "25-35",
      membership_context: "Newer player comparing lesson options",
      communication_style: "Friendly but detail-oriented",
      initial_emotion: "curious",
      patience_level: "high",
    },
    situationSummary: "A member or prospect wants to know what lesson format fits them, what the next booking step is, and how to get on the right coach’s schedule.",
    openingLine: "I’m interested in lessons, but I don’t know whether I need private instruction or something more basic first.",
    hiddenFacts: [
      "The person is mostly nervous about wasting money on the wrong format.",
    ],
    approvedResolutionPaths: [
      "Ask one or two questions about experience and goals.",
      "Recommend the right lesson path without overcommitting.",
      "Give the correct next booking step.",
    ],
    requiredBehaviors: [
      "Keep the explanation simple.",
      "Match the recommendation to the customer’s level.",
      "Close with a clear action.",
    ],
    criticalErrors: [
      "Recommend a lesson package without understanding the goal.",
      "Invent coach availability or pricing.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Customer shares their comfort level.",
      if_answer_is_vague: "Customer says they still do not know what to book.",
      if_policy_is_wrong: "Customer questions trust in the process.",
      if_employee_takes_ownership: "Customer is ready to book or follow up.",
      if_employee_fails_to_help: "Customer says they will look elsewhere.",
      if_employee_escalates_correctly: "Customer accepts a coach callback if schedule confirmation is needed.",
    },
    emotionProgression: {
      starting_state: "curious",
      better_if: ["Clear recommendation", "Simple next step"],
      worse_if: ["Jargon", "Overcomplication"],
    },
    completionRules: {
      resolved_if: ["Customer knows what lesson path to take next"],
      end_early_if: ["Employee gives unclear or contradictory direction"],
      manager_required_if: ["Package exception or coach conflict requires approval"],
    },
    recommendedTurns: 3,
  },
  {
    title: "Golf Range Service Complaint",
    department: "golf",
    scenarioFamily: "range_complaint",
    targetRole: departmentRoles.golf,
    difficulty: 3,
    emotionalIntensity: "moderate",
    complexity: "mixed",
    customerPersona: {
      name: "Owen Daniels",
      age_band: "30-40",
      membership_context: "Frequent range user",
      communication_style: "Blunt and annoyed",
      initial_emotion: "frustrated",
      patience_level: "moderate",
    },
    situationSummary: "A golfer says the range experience was poor due to balls, bay condition, or communication and wants a useful response, not excuses.",
    openingLine: "I paid to practice and the range setup was a mess. What exactly are you going to do about it?",
    hiddenFacts: [
      "The range team did have an equipment delay earlier in the shift.",
      "A reasonable service recovery may be available if the employee handles it correctly.",
    ],
    approvedResolutionPaths: [
      "Acknowledge the disruption.",
      "Clarify the operational problem without making excuses.",
      "Offer the right recovery or escalation if policy allows it.",
    ],
    requiredBehaviors: [
      "Take ownership for the service miss.",
      "Avoid defensiveness.",
      "Give a specific next step.",
    ],
    criticalErrors: [
      "Argue that the issue was not significant.",
      "Promise a credit without verifying authority.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Customer gives specifics instead of venting.",
      if_answer_is_vague: "Customer asks for a manager.",
      if_policy_is_wrong: "Customer challenges the employee’s authority.",
      if_employee_takes_ownership: "Customer accepts the recovery path.",
      if_employee_fails_to_help: "Customer threatens not to return.",
      if_employee_escalates_correctly: "Customer waits for the handoff.",
    },
    emotionProgression: {
      starting_state: "frustrated",
      better_if: ["Specific recovery", "Ownership"],
      worse_if: ["Excuses", "Minimizing"],
    },
    completionRules: {
      resolved_if: ["Customer understands the recovery path"],
      end_early_if: ["Employee denies the service issue"],
      manager_required_if: ["Requested recovery exceeds employee authority"],
    },
    recommendedTurns: 4,
  },
  {
    title: "Golf Refund or Credit Request",
    department: "golf",
    scenarioFamily: "refund_credit_request",
    targetRole: departmentRoles.golf,
    difficulty: 3,
    emotionalIntensity: "moderate",
    complexity: "mixed",
    customerPersona: {
      name: "Lauren Reed",
      age_band: "40-50",
      membership_context: "Member asking for credit after a disrupted lesson or practice experience",
      communication_style: "Measured but firm",
      initial_emotion: "frustrated",
      patience_level: "moderate",
    },
    situationSummary: "A member wants a golf-related refund or credit and expects the employee to know what is actually allowed versus what needs review.",
    openingLine: "If that lesson or range session didn’t go as promised, why shouldn’t I get a credit today?",
    hiddenFacts: [
      "The member’s account notes support some service recovery, but not an automatic full refund.",
    ],
    approvedResolutionPaths: [
      "Verify the request before promising money.",
      "Explain what can be credited now and what needs manager review.",
      "Close with a timeline or handoff.",
    ],
    requiredBehaviors: [
      "Stay concrete about authority limits.",
      "Avoid sounding evasive.",
      "Offer the next step confidently.",
    ],
    criticalErrors: [
      "Promise a dollar amount without verification.",
      "Dismiss the request without checking policy.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Member listens to the review path.",
      if_answer_is_vague: "Member says the employee is dodging the question.",
      if_policy_is_wrong: "Member asks for the manager immediately.",
      if_employee_takes_ownership: "Member accepts follow-up timing.",
      if_employee_fails_to_help: "Member threatens to escalate publicly.",
      if_employee_escalates_correctly: "Member accepts a handoff.",
    },
    emotionProgression: {
      starting_state: "frustrated",
      better_if: ["Clear authority", "Specific timing"],
      worse_if: ["Guessing", "Stonewalling"],
    },
    completionRules: {
      resolved_if: ["Member knows the actual review or credit path"],
      end_early_if: ["Employee promises money without authority"],
      manager_required_if: ["Exception or larger credit requires approval"],
    },
    recommendedTurns: 4,
  },
  {
    title: "Golf Value Explanation For Fit and Frequency",
    department: "golf",
    scenarioFamily: "value_explanation",
    targetRole: departmentRoles.golf,
    difficulty: 3,
    emotionalIntensity: "low",
    complexity: "mixed",
    customerPersona: {
      name: "Sam Whitfield",
      age_band: "35-45",
      membership_context: "Prospect weighing family schedule and cost",
      communication_style: "Thoughtful and skeptical",
      initial_emotion: "neutral",
      patience_level: "high",
    },
    situationSummary: "A prospect wants a clear explanation of where the golf offering creates value for how they actually use the club.",
    openingLine: "I’m not looking for a sales pitch. Tell me where the value actually shows up for someone like me.",
    hiddenFacts: [
      "The prospect is most interested in practice convenience and family use windows.",
    ],
    approvedResolutionPaths: [
      "Ask one or two focused discovery questions.",
      "Tie the answer to the prospect’s usage pattern.",
      "Offer a relevant next step instead of overselling.",
    ],
    requiredBehaviors: [
      "Be specific.",
      "Avoid generic amenities language.",
      "Keep the explanation grounded in the prospect’s priorities.",
    ],
    criticalErrors: [
      "Use a canned sales script.",
      "Invent benefits or pricing.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Prospect explains priorities.",
      if_answer_is_vague: "Prospect says they still do not see the value.",
      if_policy_is_wrong: "Prospect questions the numbers.",
      if_employee_takes_ownership: "Prospect asks about next steps.",
      if_employee_fails_to_help: "Prospect disengages.",
      if_employee_escalates_correctly: "Prospect accepts follow-up if the fit needs a specialist.",
    },
    emotionProgression: {
      starting_state: "neutral",
      better_if: ["Relevant discovery", "Specific fit"],
      worse_if: ["Generic pitch", "Overtalking"],
    },
    completionRules: {
      resolved_if: ["Prospect understands the value case for their own use"],
      end_early_if: ["Employee relies on generic sales language"],
      manager_required_if: ["Pricing exception or custom package is requested"],
    },
    recommendedTurns: 4,
  },
  {
    title: "MOD Slippery Entry Hazard Response",
    department: "mod_emergency",
    scenarioFamily: "slippery_entry_complaint",
    targetRole: departmentRoles.mod_emergency,
    difficulty: 4,
    emotionalIntensity: "high",
    complexity: "mixed",
    customerPersona: {
      name: "Brenda Rodriguez",
      age_band: "40-50",
      membership_context: "Morning member arriving with a child",
      communication_style: "Agitated and safety-focused",
      initial_emotion: "alarmed",
      patience_level: "low",
    },
    situationSummary: "A member reports a slippery entry area that nearly caused a fall and wants immediate action from the MOD.",
    openingLine: "Someone is going to get hurt if that entry stays like this. What are you doing right now?",
    hiddenFacts: [
      "No one is injured yet, but the hazard is real and visible.",
      "The member mainly wants to know the area is being secured now.",
    ],
    approvedResolutionPaths: [
      "Confirm whether anyone is hurt.",
      "State that the area is being secured and cleaned immediately.",
      "Document and escalate as a safety event.",
    ],
    requiredBehaviors: [
      "Lead with safety control.",
      "Sound decisive.",
      "Avoid debating the complaint.",
    ],
    criticalErrors: [
      "Focus on excuses before safety steps.",
      "Leave the hazard open while talking about follow-up.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Member becomes more factual.",
      if_answer_is_vague: "Member asks whether anyone is actually responding.",
      if_policy_is_wrong: "Member demands the GM or corporate contact.",
      if_employee_takes_ownership: "Member waits for the action plan.",
      if_employee_fails_to_help: "Member becomes less confident that the hazard is being handled.",
      if_employee_escalates_correctly: "Member accepts the incident follow-up.",
    },
    emotionProgression: {
      starting_state: "alarmed",
      better_if: ["Immediate hazard control", "Clear communication"],
      worse_if: ["Delay", "Excuses"],
    },
    completionRules: {
      resolved_if: ["Hazard control and reporting are clearly underway"],
      end_early_if: ["Employee minimizes the hazard"],
      manager_required_if: ["Always handled as MOD-level incident communication"],
    },
    recommendedTurns: 4,
  },
  {
    title: "MOD Power Interruption Member Briefing",
    department: "mod_emergency",
    scenarioFamily: "power_interruption_confusion",
    targetRole: departmentRoles.mod_emergency,
    difficulty: 4,
    emotionalIntensity: "moderate",
    complexity: "ambiguous",
    customerPersona: {
      name: "Trevor Bell",
      age_band: "30-40",
      membership_context: "Member interrupted mid-workout",
      communication_style: "Demanding and impatient",
      initial_emotion: "unsettled",
      patience_level: "low",
    },
    situationSummary: "A member wants answers during a power disruption and expects a clear status update even though some facts are still developing.",
    openingLine: "Nobody is telling us what’s going on. Are we leaving or not?",
    hiddenFacts: [
      "Estimated restoration time is not confirmed yet.",
      "The safe answer is what is open, what is closed, and when the next update will come.",
    ],
    approvedResolutionPaths: [
      "State the known facility status clearly.",
      "Avoid guessing on restoration timing.",
      "Commit to the next operational update.",
    ],
    requiredBehaviors: [
      "Stay composed under pressure.",
      "Communicate only confirmed facts.",
      "Give the member a practical next step.",
    ],
    criticalErrors: [
      "Invent a restoration timeline.",
      "Tell members everything is fine without confirming status.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Member listens to the update.",
      if_answer_is_vague: "Member accuses staff of hiding information.",
      if_policy_is_wrong: "Member demands higher leadership immediately.",
      if_employee_takes_ownership: "Member accepts the next update window.",
      if_employee_fails_to_help: "Member becomes more unsettled and presses for a clearer update.",
      if_employee_escalates_correctly: "Member accepts the handoff if needed.",
    },
    emotionProgression: {
      starting_state: "unsettled",
      better_if: ["Clear status", "No guessing"],
      worse_if: ["Speculation", "Confusing updates"],
    },
    completionRules: {
      resolved_if: ["Member understands current status and next update timing"],
      end_early_if: ["Employee guesses or contradicts facility status"],
      manager_required_if: ["Handled as MOD communication lead when disruption affects operations"],
    },
    recommendedTurns: 4,
  },
  {
    title: "MOD Unsafe Equipment Shutdown",
    department: "mod_emergency",
    scenarioFamily: "unsafe_equipment_report",
    targetRole: departmentRoles.mod_emergency,
    difficulty: 5,
    emotionalIntensity: "high",
    complexity: "ambiguous",
    customerPersona: {
      name: "Jordan Keller",
      age_band: "25-35",
      membership_context: "Regular fitness member",
      communication_style: "Alarmed and urgent",
      initial_emotion: "alarmed",
      patience_level: "low",
    },
    situationSummary: "A member reports equipment that appears unsafe and expects the MOD to shut it down and control the area immediately.",
    openingLine: "That machine is not safe. Why is it still available for people to use?",
    hiddenFacts: [
      "The equipment has not yet been tagged out.",
      "The member saw another person nearly use it again.",
    ],
    approvedResolutionPaths: [
      "Confirm the immediate risk.",
      "State that the equipment will be blocked or tagged out now.",
      "Document and escalate to facilities or maintenance.",
    ],
    requiredBehaviors: [
      "Take control quickly.",
      "Prioritize hazard removal over explanation.",
      "Communicate the next operational step clearly.",
    ],
    criticalErrors: [
      "Leave the equipment available while discussing paperwork.",
      "Minimize the report without inspecting or securing the area.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Member stays focused on the hazard.",
      if_answer_is_vague: "Member asks whether the employee is actually shutting it down.",
      if_policy_is_wrong: "Member asks for higher escalation.",
      if_employee_takes_ownership: "Member calms once shutdown is clear.",
      if_employee_fails_to_help: "Member starts warning others because they do not trust the area is secured.",
      if_employee_escalates_correctly: "Member accepts the update plan.",
    },
    emotionProgression: {
      starting_state: "alarmed",
      better_if: ["Immediate shutdown", "Clear action"],
      worse_if: ["Delay", "Minimizing"],
    },
    completionRules: {
      resolved_if: ["Hazard is clearly being taken out of service"],
      end_early_if: ["Employee leaves the hazard active"],
      manager_required_if: ["Always MOD-led when active equipment risk exists"],
    },
    recommendedTurns: 4,
  },
  {
    title: "MOD Weather and Range Closure Communication",
    department: "mod_emergency",
    scenarioFamily: "weather_range_incident",
    targetRole: departmentRoles.mod_emergency,
    difficulty: 4,
    emotionalIntensity: "moderate",
    complexity: "mixed",
    customerPersona: {
      name: "Tom Harrington",
      age_band: "50-60",
      membership_context: "Golfer upset about a range interruption",
      communication_style: "Argumentative and skeptical",
      initial_emotion: "skeptical",
      patience_level: "low",
    },
    situationSummary: "A member pushes back on a weather-related range closure and wants the MOD to reopen or make an exception.",
    openingLine: "It’s barely raining. Why are you shutting the range down right when we got here?",
    hiddenFacts: [
      "Closure is based on active lightning protocol, not just rain.",
      "The member mainly needs a firm safety explanation and the next update path.",
    ],
    approvedResolutionPaths: [
      "State the safety restriction clearly.",
      "Do not negotiate around the closure rule.",
      "Offer the correct update, credit, or rebooking path if available.",
    ],
    requiredBehaviors: [
      "Be firm without escalating the tone.",
      "Use safety reasoning, not personal opinion.",
      "Give a clear next step.",
    ],
    criticalErrors: [
      "Suggest the rule is optional.",
      "Promise reopening timing without confirmation.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Member still disagrees but listens.",
      if_answer_is_vague: "Member pushes for an exception.",
      if_policy_is_wrong: "Member asks for senior leadership.",
      if_employee_takes_ownership: "Member asks about the next update instead of reopening.",
      if_employee_fails_to_help: "Member becomes more argumentative about whether the closure is being handled fairly.",
      if_employee_escalates_correctly: "Member accepts the handoff.",
    },
    emotionProgression: {
      starting_state: "skeptical",
      better_if: ["Firm safety explanation", "Clear next update"],
      worse_if: ["Waffling", "Guessing"],
    },
    completionRules: {
      resolved_if: ["Member understands the closure is safety-driven and knows the next step"],
      end_early_if: ["Employee implies the closure can be ignored"],
      manager_required_if: ["MOD remains the decision point for safety closures"],
    },
    recommendedTurns: 4,
  },
  {
    title: "MOD Emergency Response Lead Call",
    department: "mod_emergency",
    scenarioFamily: "emergency_response",
    targetRole: departmentRoles.mod_emergency,
    difficulty: 5,
    emotionalIntensity: "high",
    complexity: "ambiguous",
    customerPersona: {
      name: "Alicia Gomez",
      age_band: "30-40",
      membership_context: "Member reporting an urgent incident",
      communication_style: "Panicked and urgent",
      initial_emotion: "alarmed",
      patience_level: "low",
    },
    situationSummary: "A member or witness reports an urgent incident and expects the MOD to control the response, secure help, and communicate clearly under pressure.",
    openingLine: "Someone just collapsed near the cardio area. I need a manager here right now.",
    hiddenFacts: [
      "The employee must lead with immediate emergency response steps, not policy explanation.",
      "The witness mainly needs clear direction and reassurance that help is moving.",
    ],
    approvedResolutionPaths: [
      "Confirm emergency response is being activated immediately.",
      "Give one or two clear directions relevant to the scene.",
      "Move quickly into incident control and internal escalation.",
    ],
    requiredBehaviors: [
      "Sound decisive and calm.",
      "Prioritize emergency steps over customer service phrasing.",
      "Avoid speculative statements.",
    ],
    criticalErrors: [
      "Delay emergency action while gathering unnecessary detail.",
      "Sound unsure about who is responding.",
    ],
    branchLogic: {
      if_empathy_is_strong: "Witness follows directions instead of spiraling.",
      if_answer_is_vague: "Witness becomes more alarmed and questions whether help is coming.",
      if_policy_is_wrong: "Witness loses trust in the response.",
      if_employee_takes_ownership: "Witness helps with directed next steps.",
      if_employee_fails_to_help: "Witness becomes more distressed and less able to follow directions.",
      if_employee_escalates_correctly: "Witness accepts the response flow.",
    },
    emotionProgression: {
      starting_state: "alarmed",
      better_if: ["Decisive control", "Simple directions"],
      worse_if: ["Delay", "Uncertainty"],
    },
    completionRules: {
      resolved_if: ["Emergency response and scene control are clearly underway"],
      end_early_if: ["Employee delays emergency action"],
      manager_required_if: ["Always"],
    },
    recommendedTurns: 4,
  },
] as const;

export const WSC_POLICY_DOCUMENT_SEEDS = [
  {
    title: "WSC Front Desk Billing and Membership Standards",
    department: "customer_service",
    scenarioFamilies: ["billing_confusion", "cancellation_request", "membership_question"],
    content: "Verify charges, notice requirements, and account details before making promises. Use short, clear explanations. Do not improvise cancellation timing, refund amounts, or exceptions. Close every front-desk financial conversation with the next update owner and time.",
    version: 3,
  },
  {
    title: "WSC Front Desk Recovery and Complaint Handling",
    department: "customer_service",
    scenarioFamilies: ["reservation_issue", "upset_parent", "member_complaint"],
    content: "Own the service miss, offer the best confirmed alternative, and avoid blaming another team. Parent concerns involving supervision or safety move to a lead or MOD quickly. Recurring complaints require documentation and a named follow-up owner.",
    version: 2,
  },
  {
    title: "WSC Golf Discovery, Lessons, and Value Positioning",
    department: "golf",
    scenarioFamilies: ["hesitant_prospect", "lesson_inquiry", "value_explanation"],
    content: "Lead with discovery, not a pitch. Match the recommendation to the golfer's goals, frequency, and fit. Do not improvise pricing or package terms. End with a concrete next step: trial, lesson booking path, or follow-up.",
    version: 2,
  },
  {
    title: "WSC Golf Credits and Range Operations",
    department: "golf",
    scenarioFamilies: ["range_complaint", "refund_credit_request"],
    content: "Acknowledge the service issue, verify what happened, and only offer credits or refunds within policy and authority. Do not guess at compensation. If the requested recovery exceeds authority, route it to the manager with clear notes.",
    version: 2,
  },
  {
    title: "WSC MOD Safety, Facility, and Emergency Response",
    department: "mod_emergency",
    scenarioFamilies: [
      "slippery_entry_complaint",
      "power_interruption_confusion",
      "unsafe_equipment_report",
      "weather_range_incident",
      "emergency_response",
    ],
    content: "Control immediate risk first, then communicate. Confirm injuries or active hazard status, secure or shut down affected areas, document the incident, and escalate internally without admitting liability. Only give confirmed operational timelines. Safety restrictions are not optional.",
    version: 4,
  },
] as const;
